### ISSUE TITLE
Should merchant names from All Merchants link be links to merchant show page?

### ISSUE THREAD

**Issue by hsmitha26** [hsmitha26/little_shop_v2#135]

**Comment by chakeresa** [comment]
@hsmitha26 I don't think so. There is no public merchant show page (only admins and the merchant themself can see info about the merchants). If you agree, let's close this issue.

**Comment by hsmitha26** [comment]
@chakeresa Thank you for looking into this and for your explanation.  I agree!  I will close this issue :)
